name: beekeep
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  image_stack: ^2.1.1
  lottie: ^2.7.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.3
  multi_select_flutter: ^4.1.3
  multi_dropdown: ^2.1.4
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26
  intl_phone_number_input: ^0.7.3+1
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_barcode_scanner: ^2.0.0
  dotted_dashed_line: ^0.0.3
  dotted_line: ^3.2.2
  flutter_image_stack: ^0.0.7
  toggle_switch: ^2.1.0
  voice_message_package: ^2.1.4
  flutter_speed_dial: ^7.0.0

  firebase_auth: ^4.17.0
  firebase_storage: ^11.6.6
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0
  fluttertoast: ^8.2.5
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  google_sign_in: ^6.2.1
  dropdown_button2: ^2.3.9
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  textfield_tags: ^3.0.1
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.0.0
  geoflutterfire_plus: ^0.0.21
  flutter_map_marker_popup: ^7.0.0
  flutterflow_paginate_firestore: ^1.0.3+1
#  barcode: ^2.2.8
#  barcode_image: ^2.0.3
#  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.3
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.3
  mobile_scanner: ^5.1.1
  barcode_widget: ^2.0.4
  googleapis_auth: ^1.6.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  app_settings: ^5.1.1
  timeago: ^3.6.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/ 

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""

# flutter_icons:
#   android: "launcher_icons"
#   ios: true
#   image_path: "assets/images/play_store_512.png"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/play_store_512.png"
  background_color: "#474747"

  # icon_size: 10

  # adaptive_icon_background: "assets/images/play_store_512.png"
  # theme_color: "#474747"
   
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/play_store_512.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/play_store_512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/play_store_512.png"